export const eventPopUpTemplate = {
    title:'事件信息',
    content:[
        {
            type:'fields',
            fieldInfos:[
                {
                    fieldName:'HName',
                    label:'名称',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                },
                {
                    fieldName:'HCityName',
                    label:'发生地',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                },
                {
                    fieldName:'Intro',
                    label:'简介',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                },
                {
                    fieldName:'STime',
                    label:'开始时间',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                },
                {
                    fieldName:'ETime',
                    label:'结束时间',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                }
            ]
        }
    ]
};

export const peoplePopUpTemplate = {
    title:'人物经历',
    content:[
        {
            type:'fields',
            fieldInfos:[
                {
                    fieldName:'Poet',
                    label:'姓名',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                },
                {
                    fieldName:'Year',
                    label:'年份',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                },
                {
                    fieldName:'Place',
                    label:'地点',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                },
                {
                    fieldName:'Content',
                    label:'经历',
                    format:{
                        places:0,
                        digitSeparator:true
                    }
                }
            ]
        }
    ]
};
