language: node_js

install:
  - npm install

script:
  - npm run build

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 51b125ca1e9d7ea91b1ac35996fad02fae77c07a  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master